FROM golang:1 AS builder

COPY . /src

RUN cd /src && \
CGO_ENABLED=0 go build -tags=viper_bind_struct -a -ldflags "-s -w -extldflags '-static'" -o delth .

FROM alpine:latest AS system

RUN apk add --no-cache -U bash tini

COPY --from=builder --chown=root:root --chmod=0755 /src/delth /usr/bin/delth

FROM traefik/whoami:latest

COPY --from=system / /

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/delth"]

CMD ["--", "/whoami"]
