# docker stack deploy -c stack-tr-main.yml traefik --prune

version: "3.7"
services:
  main:
    image: traefik:v3.1
    # healthcheck:
    #   test: wget --quiet --tries=1 --spider https://traefik.labs.cometari.eu/ping || exit 1
    #   interval: 3s
    #   timeout: 1s
    #   retries: 3
    #   start_period: 1s
    ports:
      - "80:80"
    configs:
      # Dynamic config
      # - source: routers-config
      #   target: /conf.d/routers.toml
      # - source: middlewares-config
      #   target: /conf.d/middlewares.toml

      # Static config
      - source: traefik-config
        target: /traefik.yml
    networks:
      - traefik-main
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        # https://docs.docker.com/compose/compose-file/#update_config
        order: start-first

      labels:
        - "traefik.enable=true" # Enable Traefik, because we disabled expose a service by default
        - "traefik.http.routers.t.rule=Host(`traefik.127.0.0.1.nip.io`)" # Tell Traefik to create routre 't' and catch all requests with given Host
        - "traefik.http.routers.t.service=api@internal" # the router 't' will forward request to service api@internal
        - "traefik.http.routers.t.entrypoints=web" # the router 't' should listen on both entrypoints
        - "traefik.http.services.t.loadbalancer.server.port=80" # the router 't' will balance incoming requests between servers listens on port 8080
        - "traefik.http.routers.ping.rule=Host(`traefik.127.0.0.1.nip.io`) && Path(`/ping`)"
        - "traefik.http.routers.ping.service=ping@internal"

networks:
  traefik-main:
    driver: overlay
    attachable: true
    name: traefik-main

configs:
  # routers-config:
  #   name: routers-config-${CONFIG:-3}
  #   file: ./conf.d/routers.toml
  # middlewares-config:
  #   name: middlewares-config-${CONFIG:-1}
  #   file: ./conf.d/middlewares.toml
  #
  traefik-config:
    name: traefik-config-${CONFIG:-9}
    file: ./traefik.yml
