[http]
    [http.routers]

    [http.services]
        [http.services.b0]
            [http.services.b0.loadBalancer]
                passHostHeader = true
                [[http.services.b0.loadBalancer.servers]]
                    url = "http://node3vm.ids/"

        [http.services.b1]
            [http.services.b1.loadBalancer] 
                passHostHeader = true
                [[http.services.b1.loadBalancer.servers]]
                    url = "http://172.16.0.52/" 

        [http.services.noop]
           [http.services.noop.loadBalancer]
             [[http.services.noop.loadBalancer.servers]]
                    url = "http://localhost"
